BEGIN;

CREATE TABLE IF NOT EXISTS "SequelizeMeta" (
  name VARCHAR(255) NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS roles (
  id_rol INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_rol VARCHAR(100) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS roles_nombre_rol_key
ON roles (nombre_rol);

CREATE TABLE IF NOT EXISTS usuarios (
  id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_rol INTEGER NOT NULL REFERENCES roles(id_rol) ON UPDATE CASCADE ON DELETE RESTRICT,
  nombre VARCHAR(100) NOT NULL,
  apellido VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL,
  contrasena VARCHAR(255) NOT NULL,
  telefono VARCHAR(20),
  estado BOOLEAN NOT NULL DEFAULT true,
  email_verificado BOOLEAN NOT NULL DEFAULT false,
  password_action_version INTEGER NOT NULL DEFAULT 0,
  oauth_login_version INTEGER NOT NULL DEFAULT 0,
  session_version INTEGER NOT NULL DEFAULT 0,
  intentos_fallidos INTEGER NOT NULL DEFAULT 0,
  bloqueo_hasta TIMESTAMP WITH TIME ZONE NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS usuarios_email_key
ON usuarios (email);

CREATE INDEX IF NOT EXISTS idx_usuarios_id_rol
ON usuarios (id_rol);

CREATE TABLE IF NOT EXISTS estados (
  id_estado INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_estado VARCHAR(100) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS estados_nombre_estado_key
ON estados (nombre_estado);

CREATE TABLE IF NOT EXISTS reacciones (
  id_reaccion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo VARCHAR(20) NOT NULL,
  descrip_tipo_reaccion VARCHAR(150) NULL,
  created_by_id INTEGER NULL,
  deleted_by_id INTEGER NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS reacciones_tipo_key
ON reacciones (tipo);

CREATE TABLE IF NOT EXISTS categorias (
  id_categoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_categoria VARCHAR(150) NOT NULL,
  created_by_id INTEGER NULL,
  deleted_by_id INTEGER NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS categorias_nombre_categoria_key
ON categorias (nombre_categoria);

CREATE TABLE IF NOT EXISTS comunas (
  id_comuna INTEGER PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS comunas_nombre_key
ON comunas (nombre);

CREATE TABLE IF NOT EXISTS barrios (
  id_barrio INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_comuna INTEGER NOT NULL REFERENCES comunas(id_comuna) ON UPDATE CASCADE ON DELETE CASCADE,
  nombre VARCHAR(180) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS barrios_id_comuna_nombre_key
ON barrios (id_comuna, nombre);

CREATE TABLE IF NOT EXISTS alertas (
  id_alerta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario INTEGER NULL REFERENCES usuarios(id_usuario) ON UPDATE CASCADE ON DELETE SET NULL,
  id_estado INTEGER NOT NULL REFERENCES estados(id_estado) ON UPDATE CASCADE ON DELETE RESTRICT,
  id_categoria INTEGER NOT NULL REFERENCES categorias(id_categoria) ON UPDATE CASCADE ON DELETE RESTRICT,
  id_comuna INTEGER NULL REFERENCES comunas(id_comuna) ON UPDATE CASCADE ON DELETE SET NULL,
  id_barrio INTEGER NULL REFERENCES barrios(id_barrio) ON UPDATE CASCADE ON DELETE SET NULL,
  titulo VARCHAR(200) NOT NULL,
  descripcion TEXT NOT NULL,
  ubicacion VARCHAR(255) NULL,
  prioridad VARCHAR(50) NULL,
  categoria VARCHAR(100) NULL,
  evidencia_url VARCHAR(500) NULL,
  evidencia_tipo VARCHAR(50) NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE NULL
);

CREATE INDEX IF NOT EXISTS idx_alertas_id_estado
ON alertas (id_estado);

CREATE INDEX IF NOT EXISTS idx_alertas_id_categoria
ON alertas (id_categoria);

CREATE INDEX IF NOT EXISTS idx_alertas_id_comuna
ON alertas (id_comuna);

CREATE INDEX IF NOT EXISTS idx_alertas_id_barrio
ON alertas (id_barrio);

CREATE TABLE IF NOT EXISTS evidencias (
  id_evidencia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_alerta INTEGER NOT NULL REFERENCES alertas(id_alerta) ON UPDATE CASCADE ON DELETE CASCADE,
  tipo_evidencia VARCHAR(100) NULL,
  url_evidencia TEXT NOT NULL,
  created_by_id INTEGER NULL,
  deleted_by_id INTEGER NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE NULL
);

CREATE INDEX IF NOT EXISTS idx_evidencias_id_alerta_created_at
ON evidencias (id_alerta, created_at);

CREATE TABLE IF NOT EXISTS comentarios (
  id_comentario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario INTEGER NOT NULL REFERENCES usuarios(id_usuario) ON UPDATE CASCADE ON DELETE CASCADE,
  id_alerta INTEGER NOT NULL REFERENCES alertas(id_alerta) ON UPDATE CASCADE ON DELETE CASCADE,
  texto_comentario TEXT NOT NULL,
  created_by_id INTEGER NULL,
  deleted_by_id INTEGER NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE NULL
);

CREATE INDEX IF NOT EXISTS idx_comentarios_id_alerta_created_at
ON comentarios (id_alerta, created_at);

CREATE TABLE IF NOT EXISTS alertas_reacciones (
  id_alerta_reaccion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_alerta INTEGER NOT NULL REFERENCES alertas(id_alerta) ON UPDATE CASCADE ON DELETE CASCADE,
  id_usuario INTEGER NOT NULL REFERENCES usuarios(id_usuario) ON UPDATE CASCADE ON DELETE CASCADE,
  id_reaccion INTEGER NOT NULL REFERENCES reacciones(id_reaccion) ON UPDATE CASCADE ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS alertas_reacciones_id_alerta_id_usuario
ON alertas_reacciones (id_alerta, id_usuario);

CREATE INDEX IF NOT EXISTS alertas_reacciones_id_alerta_id_reaccion
ON alertas_reacciones (id_alerta, id_reaccion);

CREATE TABLE IF NOT EXISTS historial_estado (
  id_historial INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_alerta INTEGER NOT NULL REFERENCES alertas(id_alerta) ON UPDATE CASCADE ON DELETE CASCADE,
  id_estado INTEGER NOT NULL REFERENCES estados(id_estado) ON UPDATE CASCADE ON DELETE RESTRICT,
  created_by_id INTEGER NULL,
  deleted_by_id INTEGER NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NULL,
  deleted_at TIMESTAMP WITH TIME ZONE NULL
);

CREATE INDEX IF NOT EXISTS idx_historial_estado_id_alerta_created_at
ON historial_estado (id_alerta, created_at);

INSERT INTO roles (nombre_rol)
VALUES
  ('Administrador'),
  ('Ciudadano'),
  ('JAC')
ON CONFLICT (nombre_rol) DO NOTHING;

INSERT INTO estados (nombre_estado, created_at, updated_at)
VALUES
  ('Pendiente', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('En Progreso', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Resuelta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Falsa Alerta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (nombre_estado) DO NOTHING;

INSERT INTO reacciones (
  tipo,
  descrip_tipo_reaccion,
  created_at,
  updated_at,
  deleted_at
)
VALUES
  (CHR(128077), 'Me gusta / Confirmo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
  (CHR(128543), 'Preocupacion', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
  (CHR(9989), 'Solucionado', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
  (CHR(9888), 'Importante', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
  (CHR(10060), 'Falsa alerta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL)
ON CONFLICT (tipo) DO NOTHING;

INSERT INTO categorias (
  nombre_categoria,
  created_at,
  updated_at,
  deleted_at
)
VALUES
  ('Infraestructura Urbana', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
  ('Riesgos y Emergencias', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
  ('Seguridad y Convivencia', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
  ('Casos Sociales y Vulnerabilidad', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
  ('Salud y Ambiente', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
  ('Alertas Comunitarias', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL)
ON CONFLICT (nombre_categoria) DO NOTHING;

INSERT INTO comunas (id_comuna, nombre)
VALUES
  (1, 'Comuna 1 - Centro'),
  (2, 'Comuna 2 - Norte'),
  (3, 'Comuna 3 - Sur')
ON CONFLICT (id_comuna) DO NOTHING;

INSERT INTO barrios (id_comuna, nombre)
VALUES
  (1, 'Centro Historico'),
  (1, 'Parque Principal'),
  (2, 'Villa Nueva'),
  (2, 'Los Alpes'),
  (3, 'San Miguel'),
  (3, 'Mirador del Sur')
ON CONFLICT (id_comuna, nombre) DO NOTHING;

INSERT INTO "SequelizeMeta" (name)
VALUES ('20260404000100-create-core-schema.js')
ON CONFLICT (name) DO NOTHING;

COMMIT;
